/**
 * @packageDocumentation
 * @hidden
 * @ignore
 * Contains al the different codes for errors.
 */

/**
 *  Different code errors.
 */
const ERROR_CODES = {
  NOT_DEFINED: 'NOT_DEFINED',
  INVALID_PARAMS: 'INVALID_PARAMS',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',

  // MODELS ERRORS.
  SAMPLE_NAME_EXISTS: 'SAMPLE_NAME_EXISTS',
  SAMPLE_NAME_BAD_LENGTH: 'SAMPLE_NAME_BAD_LENGTH',
  SAMPLE_NAME_NOT_VALID: 'SAMPLE_NAME_NOT_VALID',
  SAMPLE_AGE_NOT_VALID: 'SAMPLE_AGE_NOT_VALID',
  SAMPLE_TEXT_NOT_VALID: 'SAMPLE_TEXT_NOT_VALID',
  SAMPLE_OTHER_INFO_INVALID_KEY_OR_VALUE: 'SAMPLE_OTHER_INFO_INVALID_KEY_OR_VALUE',

  // SERVICES
  OTHER_SERVICE_INVALID_RESPONSE: 'OTHER_SERVICE_INVALID_RESPONSE',
  OTHER_SERVICE_ERROR: 'OTHER_SERVICE_ERROR',

  // API ERRORS.
  API_ONLY_HTTPS: 'API_ONLY_HTTPS',
  API_METHOD_NOT_FOUND: 'API_METHOD_NOT_FOUND',
  API_REQUESTS_TOO_OFTEN: 'API_REQUESTS_TOO_OFTEN',
  API_INVALID_PARAMS: 'API_INVALID_PARAMS',
};

export default ERROR_CODES;
